// src/components/Popup.tsx
import {
  CssBaseline,
  FormControlLabel,
  FormGroup,
  GlobalStyles,
  Switch,
  Typography,
} from '@mui/material'
import type { ChangeEvent } from 'react'
import StoreProvider from '~/providers/StoreProvider'
import { useAppDispatch, useAppSelector } from '~/store'
import {
  selectElapsedTime,
  selectSeekButtonsEnabled,
  selectTimestampAnchor,
  setElapsedTime,
  setSeekButtonsEnabled,
  setTimestampAnchor,
} from '~/store/settings'

const App = () => {
  const elapsedTime = useAppSelector(selectElapsedTime)
  const seekButtonsEnabled = useAppSelector(selectSeekButtonsEnabled)
  const timestampAnchor = useAppSelector(selectTimestampAnchor)
  const dispatch = useAppDispatch()

  const handleChangeElapsedTime = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setElapsedTime(value))
  }

  const handleChangeSeekButtonsEnabled = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setSeekButtonsEnabled(value))
  }

  const handleChangeTimestampAnchor = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setTimestampAnchor(value))
  }

  return (
    <FormGroup sx={{ mx: 2, my: 1 }}>
      <Typography variant="subtitle2">Player</Typography>
      <FormControlLabel
        control={
          <Switch
            checked={seekButtonsEnabled}
            onChange={handleChangeSeekButtonsEnabled}
          />
        }
        label="Add Buttons for Seeking Forward and Backward"
      />
      <Typography variant="subtitle2">Info</Typography>
      <FormControlLabel
        control={
          <Switch checked={elapsedTime} onChange={handleChangeElapsedTime} />
        }
        label="Always Show Elapsed Time"
      />
      <Typography variant="subtitle2">Comments</Typography>
      <FormControlLabel
        control={
          <Switch
            checked={timestampAnchor}
            onChange={handleChangeTimestampAnchor}
          />
        }
        label="Donot Scroll on Click Timestamp"
      />
    </FormGroup>
  )
}

const Popup = () => {
  return (
    <StoreProvider>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { overflowY: 'hidden', width: 460 },
        }}
      />
      <App />
    </StoreProvider>
  )
}

export default Popup

// src/pages/popup.vue
<template>
  <v-app>
    <v-content class="fill-height">
      <v-container fluid pa-0>
        <v-subheader>Player</v-subheader>
        <v-switch
          v-model="seekButtonsEnabled"
          label="Add Buttons for Seeking Forward and Backward"
          dense
          class="px-4 mt-0"
        />
        <!-- <v-switch
          v-model="videoQualityFixed"
          label="Always Play at The Highest Video Quality"
          dense
          class="px-4 mt-0"
        /> -->
        <v-subheader>Info</v-subheader>
        <v-switch
          v-model="elapsedTime"
          label="Always Show Elapsed Time"
          dense
          class="px-4 mt-0"
        />
        <v-subheader>Chat</v-subheader>
        <v-switch
          v-model="reloadButtonEnabled"
          label="Add Button for Reloading Chat Frame"
          dense
          class="px-4 mt-0"
        />
        <v-subheader>Comments</v-subheader>
        <v-switch
          v-model="timestampAnchor"
          label="Donot Scroll on Click Timestamp"
          dense
          class="px-4 mt-0"
        />
        <!-- <v-switch
          v-model="forceScrollButtonEnabled"
          label="Add Button for Enabling Force Scroll"
          class="mt-0 px-4"
          dense
        /> -->
      </v-container>
    </v-content>
  </v-app>
</template>

<script lang="ts">
import { Vue, Component } from 'vue-property-decorator'
import { settingsStore } from '~/store'

@Component
export default class Popup extends Vue {
  get seekButtonsEnabled() {
    return settingsStore.seekButtonsEnabled
  }
  set seekButtonsEnabled(value) {
    settingsStore.setSeekButtonsEnabled({
      seekButtonsEnabled: value,
    })
  }
  get elapsedTime() {
    return settingsStore.elapsedTime
  }
  set elapsedTime(value) {
    settingsStore.setElapsedTime({
      elapsedTime: value,
    })
  }
  get timestampAnchor() {
    return settingsStore.timestampAnchor
  }
  set timestampAnchor(value) {
    settingsStore.setTimestampAnchor({
      timestampAnchor: value,
    })
  }
  get videoQualityFixed() {
    return settingsStore.videoQualityFixed
  }
  set videoQualityFixed(value) {
    settingsStore.setVideoQualityFixed({
      videoQualityFixed: value,
    })
  }
  get reloadButtonEnabled() {
    return settingsStore.reloadButtonEnabled
  }
  set reloadButtonEnabled(value) {
    settingsStore.setReloadButtonEnabled({
      reloadButtonEnabled: value,
    })
  }
  get forceScrollButtonEnabled() {
    return settingsStore.forceScrollButtonEnabled
  }
  set forceScrollButtonEnabled(value) {
    settingsStore.setForceScrollButtonEnabled({
      forceScrollButtonEnabled: value,
    })
  }
}
</script>

<style lang="scss">
html,
body {
  height: 100%;
  margin: 0;
  padding: 0;
}
html {
  overflow-y: hidden;
}
</style>

<style lang="scss" scoped>
.v-application {
  min-width: 480px;
  .v-content ::v-deep .v-content__wrap {
    overflow-y: auto;
  }
}
</style>
