// src/components/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useStore } from '~/store'

const store = useStore()

const seekButtonsEnabled = computed({
  get: () => store.state.settings.seekButtonsEnabled,
  set: (value) =>
    store.commit('settings/setSeekButtonsEnabled', {
      seekButtonsEnabled: value,
    }),
})
const elapsedTime = computed({
  get: () => store.state.settings.elapsedTime,
  set: (value) =>
    store.commit('settings/setElapsedTime', {
      elapsedTime: value,
    }),
})
const timestampAnchor = computed({
  get: () => store.state.settings.timestampAnchor,
  set: (value) =>
    store.commit('settings/setTimestampAnchor', {
      timestampAnchor: value,
    }),
})
</script>

<template>
  <v-app>
    <v-main class="fill-height">
      <v-container fluid>
        <v-subheader>Player</v-subheader>
        <v-switch
          v-model="seekButtonsEnabled"
          color="primary"
          density="compact"
          hide-details
          label="Add Buttons for Seeking Forward and Backward"
        />
        <v-subheader>Info</v-subheader>
        <v-switch
          v-model="elapsedTime"
          color="primary"
          density="compact"
          hide-details
          label="Always Show Elapsed Time"
        />
        <v-subheader>Comments</v-subheader>
        <v-switch
          v-model="timestampAnchor"
          color="primary"
          density="compact"
          hide-details
          label="Donot Scroll on Click Timestamp"
        />
      </v-container>
    </v-main>
  </v-app>
</template>

<style lang="scss">
html {
  overflow-y: hidden;
}
</style>

<style lang="scss" scoped>
.v-application {
  min-width: 480px;
}
</style>

// src/components/App.tsx
import {
  CssBaseline,
  FormControlLabel,
  FormGroup,
  GlobalStyles,
  Switch,
  Typography,
} from '@mui/material'
import { ChangeEvent } from 'react'
import { StoreProvider } from '~/contexts/StoreContext'
import { useAppDispatch, useAppSelector } from '~/store'
import {
  selectElapsedTime,
  selectSeekButtonsEnabled,
  selectTimestampAnchor,
  setElapsedTime,
  setSeekButtonsEnabled,
  setTimestampAnchor,
} from '~/store/settings'

const InnerApp = () => {
  const elapsedTime = useAppSelector(selectElapsedTime)
  const seekButtonsEnabled = useAppSelector(selectSeekButtonsEnabled)
  const timestampAnchor = useAppSelector(selectTimestampAnchor)
  const dispatch = useAppDispatch()

  const handleChangeElapsedTime = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setElapsedTime(value))
  }

  const handleChangeSeekButtonsEnabled = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setSeekButtonsEnabled(value))
  }

  const handleChangeTimestampAnchor = (e: ChangeEvent<HTMLInputElement>) => {
    const value = e.currentTarget.checked
    dispatch(setTimestampAnchor(value))
  }

  return (
    <FormGroup sx={{ mx: 2, my: 1 }}>
      <Typography variant="subtitle2">Player</Typography>
      <FormControlLabel
        control={
          <Switch
            checked={seekButtonsEnabled}
            onChange={handleChangeSeekButtonsEnabled}
          />
        }
        label="Add Buttons for Seeking Forward and Backward"
      />
      <Typography variant="subtitle2">Info</Typography>
      <FormControlLabel
        control={
          <Switch checked={elapsedTime} onChange={handleChangeElapsedTime} />
        }
        label="Always Show Elapsed Time"
      />
      <Typography variant="subtitle2">Comments</Typography>
      <FormControlLabel
        control={
          <Switch
            checked={timestampAnchor}
            onChange={handleChangeTimestampAnchor}
          />
        }
        label="Donot Scroll on Click Timestamp"
      />
    </FormGroup>
  )
}

const App = () => {
  return (
    <StoreProvider>
      <CssBaseline />
      <GlobalStyles
        styles={{
          html: { overflowY: 'hidden', width: 460 },
        }}
      />
      <InnerApp />
    </StoreProvider>
  )
}

export default App
